### ISSUE TITLE
Is it possible to develop support for Dart

### ISSUE THREAD

**Issue by yinshaoqian** [bmalehorn/vscode-print-it#2]

**Comment by bmalehorn** [comment]
@yinshaoqian Sure, that shouldn't be too hard.

But I'm not familiar with dart. How would you print a variable? Would it look like this?

```dart
var x = 5;
print("x = ${x}");
```

**Comment by bmalehorn** [comment]
@yinshaoqian Closing this ticket due to inactivity.

As a workaround, you can set the default language formatting with something like this:

```json
"print-it.default.template": "print(\"{{escaped}} = ${ {{raw}} }\");"
```
