### ISSUE TITLE
new featrue want

### ISSUE THREAD

**Issue by lclslsls** [bmalehorn/vscode-print-it#4]
hey i was work whit c 
and it dont work very wile 
can it have a  “other” mod
any Language not in it ,can manul it in  "other opthion "

**Comment by bmalehorn** [comment]
Good idea. It would look like this:

```json
"print-it.default.template": "printf(\"{{escaped}} %s\\n\", {{raw}});"
```

@lclslsls Do you like that idea?

**Comment by bmalehorn** [comment]
I've now added the `print-it.default.template` option.

**Comment by lclslsls** [comment]
brilliant 
 id love it
